import { nextBestMission } from './decision-engine'
import type { CalendarCommitment, NexusMission, NexusWorkspace } from '../types/nexus'
export type CalendarOccurrence={id:string;sourceId:string;title:string;category:string;note:string|null;start:Date;end:Date;isFixed:boolean;isOptional:boolean}
export type RoutineSuggestion={kind:'commitment'|'focus'|'transition'|'recovery'|'personal'|'social'|'hair'|'family'|'shutdown'|'free';title:string;detail:string;durationMinutes?:number;missionId?:string;actionPath?:string;actionLabel?:string;optional?:boolean}
export type RoutineContext={now:Date;current:CalendarOccurrence|null;next:CalendarOccurrence|null;today:CalendarOccurrence[];upcoming:CalendarOccurrence[];freeMinutes:number;loadMinutes:number;load:'leve'|'normal'|'cheio';nextExam:CalendarOccurrence|null;daysToExam:number|null;suggestion:RoutineSuggestion;later:RoutineSuggestion|null}
const TZ='America/Sao_Paulo',DAY_MS=86_400_000
function localYmd(date:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
function localWeekday(date:Date){const key=new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'short'}).format(date);return ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(key)}
function localHour(date:Date){return Number(new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'2-digit',hour12:false}).format(date))%24}
function clock(value:Date){return new Intl.DateTimeFormat('pt-BR',{timeZone:TZ,hour:'2-digit',minute:'2-digit'}).format(value)}
function atTime(ymd:string,value:string){return new Date(`${ymd}T${value.slice(0,8)}-03:00`)}
function voice<T>(items:T[],date:Date){return items[localHour(date)%items.length]}
function recurringOccurrence(item:CalendarCommitment,day:Date):CalendarOccurrence|null{if(!item.start_time||!item.end_time||!item.weekdays.length)return null;const ymd=localYmd(day);if(item.active_from&&ymd<item.active_from)return null;if(item.active_until&&ymd>item.active_until)return null;if(!item.weekdays.includes(localWeekday(day)))return null;return{id:`${item.id}:${ymd}`,sourceId:item.id,title:item.title,category:item.category,note:item.note,start:atTime(ymd,item.start_time),end:atTime(ymd,item.end_time),isFixed:item.is_fixed,isOptional:item.is_optional}}
export function occurrencesForDay(commitments:CalendarCommitment[],day:Date){const ymd=localYmd(day),output:CalendarOccurrence[]=[];commitments.forEach(item=>{if(item.starts_at&&item.ends_at){const start=new Date(item.starts_at),end=new Date(item.ends_at),endProbe=new Date(end.getTime()-1000);if(ymd>=localYmd(start)&&ymd<=localYmd(endProbe))output.push({id:item.id,sourceId:item.id,title:item.title,category:item.category,note:item.note,start,end,isFixed:item.is_fixed,isOptional:item.is_optional});return}const occurrence=recurringOccurrence(item,day);if(occurrence)output.push(occurrence)});return output.sort((a,b)=>a.start.getTime()-b.start.getTime())}
export function upcomingOccurrences(commitments:CalendarCommitment[],now=new Date(),days=8){const output:CalendarOccurrence[]=[];for(let index=0;index<days;index+=1){const day=new Date(now);day.setDate(day.getDate()+index);occurrencesForDay(commitments,day).forEach(item=>{if(item.end>now)output.push(item)})}return output.sort((a,b)=>a.start.getTime()-b.start.getTime())}
function isStudyLike(category:string){return['school','class','study','exam'].includes(category)}
function isTimedCommitment(event:CalendarOccurrence){return event.end.getTime()-event.start.getTime()<20*60*60_000}
function isBlocking(event:CalendarOccurrence){return !event.isOptional&&isTimedCommitment(event)}
function relevantStudyMission(missions:NexusMission[],now:Date){const schoolWords=/estud|escola|matem|hist[oó]r|qu[ií]m|reda[cç][aã]o|bio|f[ií]sic|geograf|filosof|sociolog|ingl[eê]s|prova|simulado|enem|ufg/i;return missions.filter(mission=>{if(['Inbox','Bloqueada','Feita','Cancelada'].includes(mission.status))return false;const text=`${mission.title} ${mission.notes??''} ${mission.context??''}`,due=mission.due_at?new Date(mission.due_at).getTime()-now.getTime():Infinity;return schoolWords.test(text)||(due>=0&&due<=7*DAY_MS)}).sort((a,b)=>{const priority={Baixa:0,Média:1,Alta:2,Crítica:3},aDue=a.due_at?new Date(a.due_at).getTime():Infinity,bDue=b.due_at?new Date(b.due_at).getTime():Infinity;return priority[b.priority]-priority[a.priority]||aDue-bDue})[0]??null}
function studySuggestion(workspace:NexusWorkspace,now:Date,day:number,freeMinutes:number,next:CalendarOccurrence|null,nextExam:CalendarOccurrence|null,daysToExam:number|null):RoutineSuggestion{const studyTarget=relevantStudyMission(workspace.missions,now),examSoon=nextExam&&daysToExam!=null&&daysToExam<=7,duration=Math.min(day===0?90:60,Math.max(25,freeMinutes-(next?20:0)));const fallbackTitle=day===2?'Matemática, História ou Química':day===5?'Redação ou revisão':'Bloco principal de estudo';const title=studyTarget?.title??(examSoon?`Preparar ${nextExam.title}`:fallbackTitle);const detail=studyTarget?.notes||(day===2?'Escolha uma matéria pela prova mais próxima, pela dificuldade ou pela dúvida que está acumulando. Um bloco bem feito já move a semana.':day===5?'Faça uma redação ou revise a prova mais próxima. Escolha uma coisa e termine bem; não precisa transformar a sexta em maratona.':'Pegue o assunto que mais merece sua atenção agora — normalmente Matemática, História ou Química — e deixe o resto para depois.');return{kind:'focus',title,detail,durationMinutes:duration,missionId:studyTarget?.id,actionPath:`/foco?minutes=${duration}${studyTarget?`&mission=${studyTarget.id}`:''}`,actionLabel:`Começar ${duration} min`}}
function suggestionForFreeWindow(workspace:NexusWorkspace,now:Date,today:CalendarOccurrence[],next:CalendarOccurrence|null,freeMinutes:number,load:RoutineContext['load'],nextExam:CalendarOccurrence|null,daysToExam:number|null):RoutineSuggestion{const day=localWeekday(now),hour=localHour(now),target=nextBestMission(workspace.missions,workspace.checkin),recentSchool=[...today].reverse().find(event=>!event.isOptional&&event.category==='school'&&event.end<=now&&now.getTime()-event.end.getTime()<=65*60_000)
if(hour>=22)return{kind:'shutdown',title:voice(['Hora de desacelerar','Feche o dia por aqui','Já deu por hoje'],now),detail:voice(['Não abra outro bloco. Guarde o que ficou para amanhã, diminua o ritmo e prepare uma noite tranquila.','O que não coube hoje pode esperar. Faça o fechamento e deixe a cabeça sair do modo tarefa.','Mais uma tarefa agora provavelmente só rouba energia de amanhã. Registre o que ficou e encerre.'],now),actionPath:'/rotinas',actionLabel:'Fechamento'}
if(recentSchool)return{kind:'recovery',title:voice(['Almoço e pausa','Troca de ritmo','Primeiro, respira'],now),detail:`Você saiu da escola às ${clock(recentSchool.end)}. ${voice(['Agora vale comer, descansar e mudar de marcha; depois o NexOS reorganiza o que vier.','Não precisa emendar uma obrigação na outra. Coma, descanse e deixe o próximo bloco chegar.','Esse intervalo não está vazio: ele é a transição. Lanche, descanso e só então o próximo passo.'],now)}`,durationMinutes:Math.min(50,freeMinutes),optional:true}
if(next&&freeMinutes<=35)return{kind:'transition',title:`Daqui a pouco: ${next.title}`,detail:`Começa às ${clock(next.start)}. ${voice(['Use esse intervalo para deslocamento, lanche, banho ou simplesmente respirar.','É uma janela curta — melhor usá-la para chegar bem ao próximo compromisso do que inventar uma tarefa.','Nada precisa caber aqui. Prepare-se para o próximo compromisso e preserve o resto do fôlego.'],now)}`,durationMinutes:freeMinutes,optional:true}
if(day===1&&hour>=19)return{kind:'personal',title:voice(['A noite é sua','Chega de cobrança por hoje','Desligar também conta'],now),detail:voice(['Depois de escola integral e inglês, preserve a noite para você, família ou algum hobby. Estudo extra só se houver algo realmente urgente amanhã.','O dia já entregou bastante. Se não existe urgência concreta para amanhã, não crie uma.','Use a noite para voltar ao seu ritmo: família, hobby, conversa ou simplesmente não fazer nada por um tempo.'],now),optional:true}
if(day===4&&hour>=19)return{kind:'personal',title:'Saia do modo estudo',detail:voice(['Plantão, Física e academia já ocuparam a tarde. Jante, fique com sua família e deixe a noite respirar.','A agenda já fez a parte dela. Agora cabe jantar, conversar e descansar sem transformar descanso em tarefa.'],now),optional:true}
if(day===3&&hour>=19)return{kind:'hair',title:'Uma janela para cuidar de você',detail:voice(['Se hoje é dia de lavar o cabelo, faça a rotina normal. Se não, não invente mais uma obrigação para a noite.','Bio Vest, redação e inglês já passaram. Se o tratamento de cabelo estiver previsto, encaixe-o; caso contrário, preserve a noite.'],now),durationMinutes:30,optional:true}
if(day===6&&hour>=12&&hour<15&&!today.some(event=>!event.isOptional&&event.category==='exam'&&event.end>now&&isTimedCommitment(event)))return{kind:'hair',title:'Sábado pede um ritmo diferente',detail:'Se esta for a semana de tratamento, faça apenas o que está previsto. Depois, a tarde fica aberta para hobby, amigos ou família.',durationMinutes:45,optional:true}
const goodStudyWindow=freeMinutes>=45&&((day===2&&hour>=14&&hour<18)||(day===5&&hour>=14&&hour<16)||(day===0&&hour>=9&&hour<16));if(goodStudyWindow)return studySuggestion(workspace,now,day,freeMinutes,next,nextExam,daysToExam)
if(day===5&&hour>=16)return{kind:'social',title:voice(['Abra espaço para alguém','Sexta não precisa virar checklist','Uma conversa vale mais que outra tarefa'],now),detail:voice(['Chame alguém para lanchar, jogar, estudar junto ou combinar algo simples. Convite concreto costuma funcionar melhor que esperar a ocasião perfeita.','Se surgir uma conversa boa, fique nela. Se quiser ver alguém, mande uma mensagem direta e simples.','Use a sexta para cultivar uma relação, sair um pouco da tela ou fazer algo que você realmente queria fazer.'],now),optional:true}
if(day===6&&hour>=15)return{kind:'social',title:'Tarde livre, sem culpa',detail:'Amigos, hobby, família ou simplesmente ficar em casa. Se quiser aproximar alguém, prefira um convite pequeno e concreto em vez de transformar isso em meta.',optional:true}
if(day===0&&hour>=16)return{kind:'family',title:'Preserve o fim do domingo',detail:'Depois do principal bloco de estudo, o resto pode ser família, hobby, descanso ou vida social. O NexOS não precisa ocupar cada espaço vazio.',optional:true}
if(load==='cheio')return{kind:'recovery',title:'Não coloque mais uma coisa aqui',detail:voice(['Seu dia já está cheio. Use o espaço que sobrou para comer, tomar banho, conversar, descansar ou fazer algo que você gosta.','A agenda já passou do ponto em que adicionar mais uma tarefa ajuda. Preserve energia para o que realmente importa.'],now),optional:true}
const urgentExam=nextExam&&daysToExam!=null&&daysToExam<=3;if(target&&freeMinutes>=45&&(urgentExam||['Alta','Crítica'].includes(target.priority))){const duration=Math.min(45,Math.max(25,freeMinutes-(next?15:0)));return{kind:'focus',title:target.title,detail:target.notes||voice(['Há espaço para um bloco curto antes do próximo compromisso.','Essa é uma boa janela para tirar essa pendência do caminho sem sacrificar o restante do dia.'],now),durationMinutes:duration,missionId:target.id,actionPath:`/foco?minutes=${duration}&mission=${target.id}`,actionLabel:`Começar ${duration} min`}}
return{kind:'free',title:voice(['Pode deixar esse espaço aberto','Nada urgente aqui','Nem todo intervalo precisa de destino'],now),detail:voice(['Você não precisa transformar cada intervalo em produtividade. Descanso, hobby, família ou conversa também fazem parte do dia.','Se nada pede sua atenção agora, não invente uma demanda. Escolha o que te faz bem ou simplesmente deixe o tempo passar.','Um calendário saudável também tem espaço sem nome. Aproveite-o como quiser.'],now),optional:true}}
export function getRoutineContext(workspace:NexusWorkspace,now=new Date()):RoutineContext{const today=occurrencesForDay(workspace.calendarCommitments,now),upcoming=upcomingOccurrences(workspace.calendarCommitments,now,10),current=today.find(item=>isBlocking(item)&&item.start<=now&&item.end>now)??null,next=upcoming.find(item=>isBlocking(item)&&item.start>now)??null,cutoff=atTime(localYmd(now),'22:00:00'),nextBoundary=next&&next.start<cutoff?next.start:cutoff,freeMinutes=Math.max(0,Math.floor((nextBoundary.getTime()-now.getTime())/60_000)),loadMinutes=today.filter(event=>isBlocking(event)&&!['sleep','recovery'].includes(event.category)).reduce((sum,event)=>sum+Math.max(0,(event.end.getTime()-event.start.getTime())/60_000),0),load:RoutineContext['load']=loadMinutes>=570?'cheio':loadMinutes>=390?'normal':'leve',nextExam=upcoming.find(item=>!item.isOptional&&item.category==='exam'&&item.start>now)??null,daysToExam=nextExam?Math.max(0,Math.ceil((nextExam.start.getTime()-now.getTime())/DAY_MS)):null,suggestion=current?{kind:'commitment' as const,title:current.title,detail:isStudyLike(current.category)||current.category==='health'?`Até ${clock(current.end)}. Agora é só estar aqui; o NexOS segura o que vem depois.`:current.note||`Até ${clock(current.end)}.`}:suggestionForFreeWindow(workspace,now,today,next,freeMinutes,load,nextExam,daysToExam),after=next?new Date(next.end.getTime()+5*60_000):new Date(now.getTime()+90*60_000),laterDay=occurrencesForDay(workspace.calendarCommitments,after),laterNext=upcomingOccurrences(workspace.calendarCommitments,after,2).find(item=>isBlocking(item)&&item.start>after)??null,later=current||next?suggestionForFreeWindow(workspace,after,laterDay,laterNext,90,load,nextExam,daysToExam):null;return{now,current,next,today,upcoming,freeMinutes,loadMinutes,load,nextExam,daysToExam,suggestion,later}}
export function formatOccurrenceTime(event:CalendarOccurrence){const sameDay=localYmd(event.start)===localYmd(event.end),date=new Intl.DateTimeFormat('pt-BR',{timeZone:TZ,weekday:'short',day:'2-digit',month:'short'}).format(event.start).replace('.','');if(!isTimedCommitment(event))return date;return sameDay?`${clock(event.start)}–${clock(event.end)}`:date}
