import { ArrowRight, ArrowUpRight, CalendarDays, CheckCircle2, Coins, Crosshair, Flame, Focus, Sparkles, Target, Zap } from 'lucide-react'
import { useMemo } from 'react'
import { SurfaceCard } from '../components/SurfaceCard'
import { ProgressRing } from '../components/ProgressRing'
import { Sparkline } from '../components/charts/Sparkline'
import { useNexus } from '../context/NexusContext'
import { navigate } from '../lib/router'
import { getReadiness, loadForecast, nextBestMission } from '../lib/decision-engine'
import { emitUI } from '../lib/ui-events'

function greeting() { const h=new Date().getHours(); return h<12?'Bom dia':h<18?'Boa tarde':'Boa noite' }
const dayLabel = new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date())

export function HomePage(){
  const {workspace,loading,error,completeMission}=useNexus(); const profile=workspace.profile
  const open=workspace.missions.filter(m=>m.status!=='Inbox'); const readiness=getReadiness(workspace.checkin); const target=nextBestMission(open,workspace.checkin); const forecast=loadForecast(open)
  const completedXp=workspace.journey?.xp_earned??0; const goal=profile?.daily_xp_goal??300; const dailyPct=Math.min(100,Math.round(completedXp/Math.max(goal,1)*100))
  const todayFocus=workspace.focusSessions.filter(s=>s.status==='completed'&&new Date(s.started_at).toDateString()===new Date().toDateString()).reduce((a,s)=>a+(s.actual_minutes??0),0)
  const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const k=d.toISOString().slice(0,10);return {label:new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(d).replace('.',''),value:workspace.activity.filter(e=>e.created_at.slice(0,10)===k).reduce((s,e)=>s+Math.max(0,e.xp_delta),0)}}),[workspace.activity])
  const routineTotal=workspace.routines.flatMap(r=>r.routine_items??[]).length; const routineDone=workspace.routineCompletions.length
  const name=profile?.display_name?.split(' ')[0]||'Gabriel'
  return <div className="page-stack home-page">
    <section className="home-hero"><div className="home-hero__ambient"/><div className="home-hero__copy"><span className="eyebrow">{dayLabel}</span><h1>{greeting()}, {name}.</h1><p>Veja o que importa agora, faça o próximo passo e deixe o restante guardado no sistema.</p><div className="hero-actions"><button className="primary-button" onClick={()=>navigate('/hoje')}>Ver meu dia <ArrowUpRight size={16}/></button><button className="secondary-button" onClick={()=>emitUI('quickAdd')}>Captura rápida</button></div>{error&&<small className="system-error">{error}</small>}</div><div className="player-compact"><div className="player-orb"><Sparkles size={22}/></div><div><span>{profile?.class_name??'Tecelão'}</span><strong>Nível {profile?.level??1}</strong><small>{profile?.title??'Iniciado da Trama'}</small></div><div className="player-coins"><Coins size={14}/><span>{profile?.nexus_coins??0}</span></div></div></section>
    <section className="home-status-grid"><div><Zap size={16}/><span>XP hoje</span><strong>{completedXp}<small> / {goal}</small></strong></div><div><Flame size={16}/><span>Disposição</span><strong>{readiness.score}<small> / 100</small></strong></div><div><Focus size={16}/><span>Foco</span><strong>{todayFocus}<small> min</small></strong></div><div><CheckCircle2 size={16}/><span>Rotina</span><strong>{routineDone}<small> / {routineTotal}</small></strong></div></section>
    <section className="home-command-grid"><SurfaceCard tone="blue" className="now-card"><div className="now-card__header"><div><span className="eyebrow">Próxima ação sugerida</span><h2>{target?target.title:'Sem missão pendente'}</h2></div><Crosshair size={19}/></div>{target?<><div className="mission-meta"><span className={`rank-chip rank-${target.rank.toLowerCase()}`}>{target.rank}</span><span>{target.duration_minutes??45} min</span><span>+{target.xp_base+target.xp_bonus} XP</span></div><p>{target.notes||readiness.note}</p><div className="now-actions"><button className="primary-button" onClick={()=>navigate('/foco')}>Começar foco <ArrowRight size={15}/></button><button className="completion-button" onClick={()=>void completeMission(target.id)}><CheckCircle2 size={16}/> Concluir</button></div></>:<><p>Não há uma missão ativa agora. Você pode revisar a Inbox ou criar a próxima ação.</p><button className="secondary-button" onClick={()=>emitUI('quickAdd')}>Criar missão</button></>}</SurfaceCard><SurfaceCard tone="violet" eyebrow="Hoje" title="Progresso da meta diária"><div className="momentum-card"><ProgressRing value={dailyPct} label="meta diária" detail={`${completedXp} XP`} size="lg"/><div className="momentum-copy"><strong>{dailyPct>=100?'Meta alcançada':dailyPct>=60?'Bom andamento':'Ainda começando'}</strong><p>{open.length} missões abertas · {todayFocus} min de foco registrado</p><button className="text-button" onClick={()=>navigate('/insights')}>Ver detalhes <ArrowUpRight size={13}/></button></div></div></SurfaceCard></section>
    <section className="split-grid split-grid--wide"><SurfaceCard eyebrow="Últimos 7 dias" title="XP registrado" tone="cyan"><Sparkline data={days}/></SurfaceCard><SurfaceCard eyebrow="Próximos pontos" title="O que merece atenção"><div className="radar-list"><button onClick={()=>navigate('/calendario')}><span className="radar-icon tone-blue"><CalendarDays size={16}/></span><div><strong>{forecast.label}</strong><small>{forecast.minutes} min com prazo nos próximos 7 dias</small></div><ArrowUpRight size={14}/></button><button onClick={()=>navigate('/rotinas')}><span className="radar-icon tone-green"><CheckCircle2 size={16}/></span><div><strong>Rotinas</strong><small>{routineDone}/{routineTotal} etapas concluídas hoje</small></div><ArrowUpRight size={14}/></button><button onClick={()=>navigate('/projetos')}><span className="radar-icon tone-violet"><Target size={16}/></span><div><strong>Projetos</strong><small>{workspace.projects.length} projetos ativos</small></div><ArrowUpRight size={14}/></button></div></SurfaceCard></section>
    <section><div className="section-heading"><div><span className="eyebrow">Projetos</span><h2>Em andamento</h2></div><button className="text-button" onClick={()=>navigate('/projetos')}>Ver todos <ArrowUpRight size={13}/></button></div><div className="project-grid">{workspace.projects.slice(0,3).map((project)=><SurfaceCard key={project.id} tone={project.progress>70?'green':project.progress>40?'blue':'violet'}><div className="project-card-modern"><div><span>{project.status}</span><strong>{project.name}</strong><p>{project.next_action||'Defina a próxima ação'}</p></div><div className="project-progress"><span style={{width:`${project.progress}%`}}/></div><footer><span>Nv. {project.level}</span><span>{project.progress}%</span><span>{project.xp} XP</span></footer></div></SurfaceCard>)}</div></section>
    {loading&&<div className="loading-line"/>}
  </div>
}
