import { ArrowRight, Inbox, Layers3, Sparkles, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'
import { emitUI } from '../lib/ui-events'

export function InboxPage() {
  const { workspace, processMission } = useNexus()
  const [busy, setBusy] = useState<string | null>(null)
  const inbox = useMemo(() => workspace.missions.filter((mission) => mission.status === 'Inbox'), [workspace.missions])
  async function move(id: string, status: 'A fazer' | 'Cancelada') { setBusy(id); try { await processMission(id, { status }) } finally { setBusy(null) } }
  return <div className="page-stack inbox-page"><section className="page-hero page-hero--amber"><div><span className="eyebrow">Anote primeiro</span><h1>Caixa de entrada</h1><p>Guarde rapidamente o que surgiu. Você decide depois se isso vira missão, projeto, compromisso ou se pode ser descartado.</p></div><div className="page-hero__badge"><Inbox size={17}/> <span>{inbox.length} pendência{inbox.length === 1 ? '' : 's'}</span></div></section><section className="inbox-command-grid"><SurfaceCard tone="amber" className="inbox-capture-card"><span className="eyebrow">Captura rápida</span><h2>Tem algo para lembrar?</h2><p>Anote agora. Projeto, prazo e prioridade podem ser decididos depois.</p><button className="primary-button" onClick={() => emitUI('quickAdd')}><Sparkles size={16}/> Capturar</button></SurfaceCard><SurfaceCard eyebrow="Ao processar" title="Faça três perguntas"><div className="inbox-rule-list"><div><strong>1.</strong><span>Isso exige uma ação?</span></div><div><strong>2.</strong><span>Qual é a próxima ação concreta?</span></div><div><strong>3.</strong><span>Precisa de prazo ou pertence a um projeto?</span></div></div></SurfaceCard></section><SurfaceCard eyebrow="Pendências" title={inbox.length ? 'Escolha o destino' : 'Tudo processado'} action={<span className="surface-chip">{inbox.length}</span>}>{inbox.length ? <div className="inbox-list">{inbox.map((item) => <article className="inbox-item" key={item.id}><div className="inbox-item__icon"><Layers3 size={16}/></div><div><strong>{item.title}</strong><span>Entrada rápida · Rank {item.rank}</span></div><div className="inbox-item__actions"><button disabled={busy===item.id} onClick={()=>move(item.id,'Cancelada')} className="icon-button" title="Descartar"><Trash2 size={15}/></button><button disabled={busy===item.id} onClick={()=>move(item.id,'A fazer')} className="secondary-button">Virar missão <ArrowRight size={14}/></button></div></article>)}</div> : <div className="empty-state-modern"><Inbox size={28}/><strong>Nada esperando decisão.</strong><span>Você não precisa manter essas coisas na cabeça.</span></div>}</SurfaceCard></div>
}
