import { ArrowRight, Inbox, Layers3, Sparkles, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'
import { emitUI } from '../lib/ui-events'

export function InboxPage() {
  const { workspace, processMission } = useNexus()
  const [busy, setBusy] = useState<string | null>(null)
  const inbox = useMemo(() => workspace.missions.filter((mission) => mission.status === 'Inbox'), [workspace.missions])
  async function move(id: string, status: 'A fazer' | 'Cancelada') { setBusy(id); try { await processMission(id, { status }) } finally { setBusy(null) } }
  return <div className="page-stack inbox-page"><section className="page-hero page-hero--amber"><div><span className="eyebrow">Capture first</span><h1>Inbox</h1><p>Um buffer deliberadamente simples. Capture em segundos e decida depois — sem obrigar sua cabeça a classificar tudo na hora.</p></div><div className="page-hero__badge"><Inbox size={17}/> {inbox.length} pendência{inbox.length === 1 ? '' : 's'}</div></section><section className="inbox-command-grid"><SurfaceCard tone="amber" className="inbox-capture-card"><span className="eyebrow">Fricção mínima</span><h2>Algo entrou na sua cabeça?</h2><p>Capture sem escolher projeto, data ou prioridade. Processar é outra tarefa.</p><button className="primary-button" onClick={() => emitUI('quickAdd')}><Sparkles size={16}/> Capturar agora</button></SurfaceCard><SurfaceCard eyebrow="Regra do sistema" title="Processar, não executar"><div className="inbox-rule-list"><div><strong>1.</strong><span>Isso exige uma ação?</span></div><div><strong>2.</strong><span>Qual é a próxima ação visível?</span></div><div><strong>3.</strong><span>Precisa de prazo, projeto ou contexto?</span></div></div></SurfaceCard></section><SurfaceCard eyebrow="Não processadas" title={inbox.length ? 'Decida o destino.' : 'Inbox zero.'} action={<span className="surface-chip">{inbox.length}</span>}>{inbox.length ? <div className="inbox-list">{inbox.map((item) => <article className="inbox-item" key={item.id}><div className="inbox-item__icon"><Layers3 size={16}/></div><div><strong>{item.title}</strong><span>Capturado como entrada rápida · Rank {item.rank}</span></div><div className="inbox-item__actions"><button disabled={busy===item.id} onClick={()=>move(item.id,'Cancelada')} className="icon-button" title="Descartar"><Trash2 size={15}/></button><button disabled={busy===item.id} onClick={()=>move(item.id,'A fazer')} className="secondary-button">Virar missão <ArrowRight size={14}/></button></div></article>)}</div> : <div className="empty-state-modern"><Inbox size={28}/><strong>Nada esperando decisão.</strong><span>Isso é bom: o sistema está confiável e você não precisa lembrar de nada fora dele.</span></div>}</SurfaceCard></div>
}
