import { ArrowRight, BarChart3, Brain, CalendarRange, Clock3, Flame, Zap } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Sparkline } from '../components/charts/Sparkline'
import { MetricBars } from '../components/charts/MetricBars'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'
import { getReadiness, pearson } from '../lib/decision-engine'
import { localDate } from '../lib/nexus-api'
import { navigate } from '../lib/router'

function lastDays(count:number){return Array.from({length:count},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(count-1-index));return date})}
const key=(date:Date)=>localDate(date)
type Range=7|30

export function InsightsPage(){
  const {workspace}=useNexus();const [range,setRange]=useState<Range>(7);const [selectedDate,setSelectedDate]=useState(()=>localDate())
  const days=useMemo(()=>lastDays(range),[range])
  const xp=days.map(day=>({label:range===7?new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(day).replace('.',''):new Intl.DateTimeFormat('pt-BR',{day:'2-digit'}).format(day),value:workspace.activity.filter(e=>e.created_at.slice(0,10)===key(day)).reduce((sum,e)=>sum+Math.max(0,e.xp_delta),0)}))
  const focus=days.map(day=>({label:range===7?new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(day).replace('.',''):new Intl.DateTimeFormat('pt-BR',{day:'2-digit'}).format(day),value:workspace.focusSessions.filter(s=>s.started_at.slice(0,10)===key(day)&&s.status==='completed').reduce((sum,s)=>sum+(s.actual_minutes??0),0)}))
  const totalXp=xp.reduce((s,d)=>s+d.value,0);const totalFocus=focus.reduce((s,d)=>s+d.value,0);const readiness=getReadiness(workspace.checkin);const activeDays=xp.filter((d,i)=>d.value>0||focus[i].value>0).length;const consistency=Math.round(activeDays/range*100);const averageXp=Math.round(totalXp/Math.max(activeDays,1))
  const xpByDate=new Map<string,number>();workspace.activity.forEach(e=>xpByDate.set(e.created_at.slice(0,10),(xpByDate.get(e.created_at.slice(0,10))??0)+Math.max(0,e.xp_delta)))
  const pairs=workspace.dailyCheckins.filter(c=>c.energy!=null).map(c=>[c.energy as number,xpByDate.get(c.checkin_date)??0] as [number,number]);const energyXp=pearson(pairs)
  const energy=workspace.dailyCheckins.slice(-range).map(c=>({label:new Date(`${c.checkin_date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:range===7?'short':undefined,day:range===30?'2-digit':undefined}).replace('.',''),value:c.energy??0,detail:c.energy?`${c.energy}/10`:'—'}));const validEnergy=workspace.dailyCheckins.slice(-range).filter(c=>c.energy!=null);const averageEnergy=validEnergy.length?(validEnergy.reduce((sum,c)=>sum+(c.energy??0),0)/validEnergy.length).toFixed(1):'—'
  const heatmap=days.map((day,index)=>({date:key(day),label:new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(day),xp:xp[index].value,focus:focus[index].value,intensity:Math.min(4,Math.ceil((xp[index].value+focus[index].value*2)/120))}))
  const selectedActivity=workspace.activity.filter(e=>e.created_at.slice(0,10)===selectedDate);const selectedFocus=workspace.focusSessions.filter(s=>s.started_at.slice(0,10)===selectedDate&&s.status==='completed');const selectedCheckin=workspace.dailyCheckins.find(c=>c.checkin_date===selectedDate);const selectedXp=selectedActivity.reduce((sum,e)=>sum+Math.max(0,e.xp_delta),0);const selectedFocusMinutes=selectedFocus.reduce((sum,s)=>sum+(s.actual_minutes??0),0)
  const selectedLabel=new Date(`${selectedDate}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})
  const dayReading=selectedFocusMinutes>120&&((selectedCheckin?.energy??10)<=5)?'Foi um dia exigente para a energia registrada. Vale observar se esse volume foi realmente necessário.':selectedFocusMinutes>0?'Há dados suficientes para entender onde o tempo de foco foi usado.':selectedXp>0?'Houve progresso registrado, mesmo sem sessão de foco.':'Pouco foi registrado neste dia — isso não significa automaticamente que o dia foi ruim ou improdutivo.'

  return <div className="page-stack insights-page insights-page--consultable">
    <section className="page-hero page-hero--cyan"><div><span className="eyebrow">Seus dados</span><h1>Insights</h1><p>Explore os dados por período e toque em qualquer dia para entender o que aconteceu de verdade, em vez de interpretar gráficos no vazio.</p></div><div className="view-switcher"><button className={range===7?'active':''} onClick={()=>setRange(7)}>7 dias</button><button className={range===30?'active':''} onClick={()=>setRange(30)}>30 dias</button></div></section>

    <section className="metrics-grid"><SurfaceCard tone="violet" className="metric-card"><div className="metric-icon"><Zap size={18}/></div><div><span>XP registrado</span><strong>{totalXp}</strong><small>{range} dias</small></div></SurfaceCard><SurfaceCard tone="blue" className="metric-card"><div className="metric-icon"><Clock3 size={18}/></div><div><span>Tempo em foco</span><strong>{totalFocus}m</strong><small>sessões concluídas</small></div></SurfaceCard><SurfaceCard tone="green" className="metric-card"><div className="metric-icon"><Flame size={18}/></div><div><span>Dias com atividade</span><strong>{consistency}%</strong><small>{activeDays}/{range} dias</small></div></SurfaceCard><SurfaceCard tone="cyan" className="metric-card"><div className="metric-icon"><Brain size={18}/></div><div><span>Energia média</span><strong>{averageEnergy}</strong><small>check-ins</small></div></SurfaceCard></section>

    <section className="split-grid split-grid--wide"><SurfaceCard tone="violet" eyebrow="XP" title="Ao longo do período"><Sparkline data={xp}/></SurfaceCard><SurfaceCard tone="blue" eyebrow="Foco" title="Minutos registrados"><Sparkline data={focus} suffix="m"/></SurfaceCard></section>

    <section className="insights-explorer">
      <SurfaceCard tone="cyan" eyebrow="Atividade" title="Escolha um dia para consultar" action={<span className="page-hero__badge"><CalendarRange size={14}/><span>{activeDays} ativos</span></span>}><div className="activity-heatmap activity-heatmap--interactive">{heatmap.map(day=><button className={`heatmap-day ${selectedDate===day.date?'selected':''}`} key={day.date} title={`${day.label}: ${day.xp} XP · ${day.focus} min`} onClick={()=>setSelectedDate(day.date)}><span className={`heatmap-cell heatmap-cell--${day.intensity}`}/><small>{range===7?day.label:new Date(`${day.date}T12:00:00`).getDate()}</small></button>)}</div><div className="heatmap-summary"><span><strong>{averageXp}</strong> XP/dia ativo</span><span><strong>{readiness.score}</strong> disposição hoje</span><span><strong>{workspace.profile?.streak_current??0}</strong> dias de sequência</span></div></SurfaceCard>

      <aside className="insight-day-inspector"><SurfaceCard tone="blue" eyebrow="Dia consultado" title={selectedLabel}><div className="insight-day-metrics"><span><strong>{selectedXp}</strong> XP</span><span><strong>{selectedFocusMinutes}m</strong> foco</span><span><strong>{selectedCheckin?.energy??'—'}</strong> energia</span></div><p className="panel-copy">{dayReading}</p><button className="text-button" onClick={()=>navigate(`/calendario?date=${selectedDate}`)}>Ver esse dia no calendário <ArrowRight size={13}/></button></SurfaceCard><SurfaceCard eyebrow="O que foi registrado" title={`${selectedActivity.length+selectedFocus.length} eventos`}><div className="insight-day-list">{selectedActivity.slice(0,8).map(e=><div key={e.id}><span className="insight-dot"/><div><strong>{e.label||e.event_type}</strong><small>{e.xp_delta?`${e.xp_delta>0?'+':''}${e.xp_delta} XP`:e.event_type}</small></div></div>)}{selectedFocus.map(s=><div key={s.id}><span className="insight-dot insight-dot--focus"/><div><strong>{s.label||'Sessão de foco'}</strong><small>{s.actual_minutes??0} min · {s.distraction_count} distrações</small></div></div>)}{!selectedActivity.length&&!selectedFocus.length&&<div className="empty-compact">Nenhum evento registrado neste dia.</div>}</div></SurfaceCard></aside>
    </section>

    <section className="split-grid"><SurfaceCard tone="green" eyebrow="Energia" title="Check-ins registrados">{energy.length?<MetricBars items={energy} max={10}/>:<div className="empty-compact">Faça check-ins em Hoje para formar este gráfico.</div>}</SurfaceCard><SurfaceCard eyebrow="Leitura" title="O que os dados sugerem"><div className="insight-list"><div><strong>Energia e XP</strong><span>{energyXp==null?'Ainda são necessários pelo menos 3 dias com check-in e atividade.':`${energyXp>0.35?'Nos dias com mais energia, o XP também tende a subir':energyXp<-0.35?'Mais energia ainda não está aparecendo como mais XP':'Ainda não há uma relação clara'} (r = ${energyXp.toFixed(2)}).`}</span></div><div><strong>Frequência de uso</strong><span>{consistency>=70?'Há registros suficientes para começar a enxergar padrões.':consistency>=40?'Já existem alguns sinais, mas ainda há lacunas no período.':'Ainda há poucos registros para tirar conclusões úteis.'}</span></div><div><strong>Tempo em foco</strong><span>{totalFocus>range*90?'O volume está alto; compare com sua energia antes de aumentar ainda mais.':'O volume pode ser ajustado de acordo com energia e compromissos.'}</span></div></div></SurfaceCard></section>
  </div>
}
