import { BarChart3, Brain, Clock3, Flame, Zap } from 'lucide-react'
import { Sparkline } from '../components/charts/Sparkline'
import { MetricBars } from '../components/charts/MetricBars'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'
import { getReadiness, pearson } from '../lib/decision-engine'
import { localDate } from '../lib/nexus-api'

function lastDays(count:number){ return Array.from({length:count},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(count-1-i));return d}) }
const key=(d:Date)=>localDate(d)

export function InsightsPage(){
  const {workspace}=useNexus(); const days=lastDays(7)
  const xp=days.map((day)=>({label:new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(day).replace('.',''),value:workspace.activity.filter(e=>e.created_at.slice(0,10)===key(day)).reduce((s,e)=>s+Math.max(0,e.xp_delta),0)}))
  const focus=days.map((day)=>({label:new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(day).replace('.',''),value:workspace.focusSessions.filter(e=>e.started_at.slice(0,10)===key(day) && e.status==='completed').reduce((s,e)=>s+(e.actual_minutes??0),0)}))
  const totalXp=xp.reduce((s,d)=>s+d.value,0); const totalFocus=focus.reduce((s,d)=>s+d.value,0); const readiness=getReadiness(workspace.checkin)
  const xpByDate = new Map<string, number>(); workspace.activity.forEach((event)=>xpByDate.set(event.created_at.slice(0,10),(xpByDate.get(event.created_at.slice(0,10))??0)+Math.max(0,event.xp_delta)))
  const energyXpPairs = workspace.dailyCheckins.filter(c=>c.energy!=null).map(c=>[c.energy as number,xpByDate.get(c.checkin_date)??0] as [number,number]); const energyXp=pearson(energyXpPairs)
  const energy=workspace.dailyCheckins.slice(-7).map(c=>({label:new Date(`${c.checkin_date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short'}).replace('.',''),value:c.energy??0,detail:c.energy?`${c.energy}/10`:'—'}))
  return <div className="page-stack"><section className="page-hero page-hero--cyan"><div><span className="eyebrow">Behavior analytics</span><h1>Insights</h1><p>Seu sistema agora pode observar padrões reais de energia, foco e execução — sem depender de memória ou sensação vaga.</p></div><div className="page-hero__badge"><BarChart3 size={17}/> 7 dias</div></section><section className="metrics-grid"><SurfaceCard tone="violet" className="metric-card"><div className="metric-icon"><Zap size={18}/></div><div><span>XP produzido</span><strong>{totalXp}</strong><small>últimos 7 dias</small></div></SurfaceCard><SurfaceCard tone="blue" className="metric-card"><div className="metric-icon"><Clock3 size={18}/></div><div><span>Foco profundo</span><strong>{totalFocus}m</strong><small>tempo registrado</small></div></SurfaceCard><SurfaceCard tone="green" className="metric-card"><div className="metric-icon"><Flame size={18}/></div><div><span>Sequência</span><strong>{workspace.profile?.streak_current??0}</strong><small>dias ativos</small></div></SurfaceCard><SurfaceCard tone="cyan" className="metric-card"><div className="metric-icon"><Brain size={18}/></div><div><span>Readiness hoje</span><strong>{readiness.score}</strong><small>{readiness.label}</small></div></SurfaceCard><SurfaceCard tone="cyan" className="metric-card"><div className="metric-icon"><Brain size={18}/></div><div><span>Energia média</span><strong>{workspace.dailyCheckins.length? (workspace.dailyCheckins.reduce((s,c)=>s+(c.energy??0),0)/workspace.dailyCheckins.filter(c=>c.energy).length || 0).toFixed(1):'—'}</strong><small>check-ins recentes</small></div></SurfaceCard></section><section className="split-grid"><SurfaceCard tone="violet" eyebrow="Output" title="XP por dia"><Sparkline data={xp}/></SurfaceCard><SurfaceCard tone="blue" eyebrow="Deep work" title="Minutos de foco"><Sparkline data={focus} suffix="m"/></SurfaceCard></section><section className="split-grid"><SurfaceCard tone="green" eyebrow="Readiness" title="Energia registrada">{energy.length?<MetricBars items={energy} max={10}/>:<div className="empty-compact">Faça check-ins em Hoje para formar sua curva de energia.</div>}</SurfaceCard><SurfaceCard eyebrow="Leitura" title="O que o sistema pode começar a aprender"><div className="insight-list"><div><strong>Melhor janela de foco</strong><span>Será calculada quando houver sessões distribuídas por horário.</span></div><div><strong>Relação energia × execução</strong><span>{energyXp==null?'Ainda são necessários pelo menos 3 dias com check-in e atividade.':`${energyXp>0.35?'Há uma relação positiva':energyXp<-0.35?'A execução não está acompanhando a energia':'A relação ainda é fraca'} (r = ${energyXp.toFixed(2)}).`}</span></div><div><strong>Carga sustentável</strong><span>Projetos, missões e rotina passam a mostrar tendência, não só estado.</span></div></div></SurfaceCard></section></div>
}
