import { ArrowRight, Award, CheckCircle2, Coins, Crosshair, LockKeyhole, Sparkles, Swords, Trophy, X, Zap } from 'lucide-react'
import { useMemo, useState } from 'react'
import { ProgressRing } from '../components/ProgressRing'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'
import { navigate } from '../lib/router'

type Selection={kind:'attribute'|'reward'|'achievement';id:string}|null

export function LifeRpgPage(){
  const {workspace,claimReward}=useNexus();const [message,setMessage]=useState<string|null>(null);const [selection,setSelection]=useState<Selection>(null);const profile=workspace.profile
  const currentLevelXp=(profile?.xp_total??0)%500;const levelPct=Math.round(currentLevelXp/500*100)
  const seasonXp=useMemo(()=>{if(!workspace.season?.starts_on)return 0;return workspace.activity.filter(e=>e.created_at.slice(0,10)>=(workspace.season?.starts_on??'')).reduce((s,e)=>s+Math.max(0,e.xp_delta),0)},[workspace.activity,workspace.season]);const seasonPct=Math.min(100,Math.round(seasonXp/Math.max(workspace.season?.xp_goal??1,1)*100));const unlocked=workspace.achievements.filter(item=>item.unlocked_at)
  const selectedAttribute=selection?.kind==='attribute'?workspace.attributes.find(a=>a.id===selection.id):null;const selectedReward=selection?.kind==='reward'?workspace.rewards.find(r=>r.id===selection.id):null;const selectedAchievement=selection?.kind==='achievement'?workspace.achievements.find(a=>a.id===selection.id):null
  const attrMissions=selectedAttribute?workspace.missions.filter(m=>m.attribute_id===selectedAttribute.id&&!['Feita','Cancelada'].includes(m.status)).slice(0,6):[]
  async function redeem(id:string){try{const reward=await claimReward(id);setMessage(`${reward} resgatada.`);setTimeout(()=>setMessage(null),3000);setSelection(null)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível resgatar.')}}
  function inspect(next:Selection){setSelection(next);if(window.matchMedia('(max-width:760px)').matches)window.setTimeout(()=>document.querySelector('.rpg-inspector')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}

  return <div className="page-stack rpg-page rpg-page--consultable">
    <section className="rpg-hero"><div className="rpg-hero__sigil"><Sparkles size={29}/></div><div className="rpg-hero__identity"><span className="eyebrow">Seu progresso</span><h1>{profile?.display_name??'Jogador'}</h1><p>{profile?.class_name??'Tecelão'} · {profile?.title??'Iniciado da Trama'}</p>{profile?.motto&&<small className="rpg-motto">“{profile.motto}”</small>}<div className="level-track"><span style={{width:`${levelPct}%`}}/></div><small>{currentLevelXp} / 500 XP para o próximo nível</small></div><div className="rpg-hero__level"><span>NÍVEL</span><strong>{profile?.level??1}</strong><div><Coins size={13}/><span>{profile?.nexus_coins??0} coins</span></div></div></section>
    {message&&<div className="toast-message">{message}</div>}

    <section className="attribute-grid attribute-grid--rpg">{workspace.attributes.map(attr=><button className={`attribute-card attribute-card--button tone-${attr.color??'slate'} ${selection?.kind==='attribute'&&selection.id===attr.id?'selected':''}`} key={attr.id} onClick={()=>inspect({kind:'attribute',id:attr.id})}><div><span>{attr.icon&&<b className="attribute-symbol">{attr.icon}</b>}{attr.label}</span><strong>Nv. {attr.level}</strong></div><p>{attr.description}</p><div className="attribute-xp-track"><span style={{width:`${(attr.xp%400)/400*100}%`}}/></div><small>{attr.xp%400} / 400 XP</small></button>)}</section>

    <section className="split-grid"><SurfaceCard tone="violet" eyebrow="Temporada" title={workspace.season?.name??'Ascensão do Nexus'}><div className="ring-row"><ProgressRing value={seasonPct} label="temporada" detail={`${seasonXp} / ${workspace.season?.xp_goal??6000} XP`} size="lg"/><div className="journey-notes"><div><Swords size={16}/><span><strong>Objetivo final</strong>{workspace.season?.boss_name??'Consolidar o sistema'}</span></div><div><Trophy size={16}/><span><strong>Recompensa</strong>{workspace.season?.final_reward??'Experiência especial'}</span></div><div><Zap size={16}/><span><strong>Missões concluídas</strong>{workspace.activity.filter(e=>e.event_type==='mission.completed').length} registradas</span></div></div></div></SurfaceCard>
      <SurfaceCard tone="amber" eyebrow="Coins" title="Recompensas"><div className="reward-list">{workspace.rewards.map(reward=><button className={`reward-card ${selection?.kind==='reward'&&selection.id===reward.id?'selected':''}`} key={reward.id} onClick={()=>inspect({kind:'reward',id:reward.id})}><span className="reward-icon"><Award size={16}/></span><div><strong>{reward.name}</strong><small>{reward.description}</small></div><span className="reward-cost"><Coins size={12}/><span>{reward.cost}</span></span></button>)}</div></SurfaceCard></section>

    <section className={`rpg-detail-workspace ${selection?'has-inspector':''}`}>
      <SurfaceCard tone="violet" eyebrow="Conquistas" title={`${unlocked.length} / ${workspace.achievements.length} desbloqueadas`}><div className="achievement-grid">{workspace.achievements.map(item=><button className={`achievement-card achievement-card--button ${item.unlocked_at?'is-unlocked':''} ${selection?.kind==='achievement'&&selection.id===item.id?'selected':''}`} key={item.id} onClick={()=>inspect({kind:'achievement',id:item.id})}><span className="achievement-card__icon">{item.unlocked_at?<CheckCircle2 size={17}/>:<LockKeyhole size={17}/>}</span><div><div className="achievement-card__title"><strong>{item.name}</strong><span>{item.rarity}</span></div><p>{item.criteria}</p><small>+{item.xp_reward} XP · +{item.coin_reward} coins</small></div></button>)}</div></SurfaceCard>

      {selection&&<aside className="rpg-inspector">
        {selectedAttribute&&<><SurfaceCard tone={selectedAttribute.color??'violet'} className="entity-inspector"><div className="entity-inspector__header"><div><span className="eyebrow">Atributo</span><h2>{selectedAttribute.icon} {selectedAttribute.label}</h2></div><button className="icon-button" onClick={()=>setSelection(null)}><X size={16}/></button></div><p className="panel-copy">{selectedAttribute.description}</p><div className="entity-inspector__meta"><span>Nv. {selectedAttribute.level}</span><span>{selectedAttribute.xp%400}/400 XP</span><span>{400-(selectedAttribute.xp%400)} XP até o próximo</span></div></SurfaceCard><SurfaceCard eyebrow="Ligação real" title={`${attrMissions.length} missões abertas`}><div className="project-linked-missions">{attrMissions.map(m=><button key={m.id} onClick={()=>navigate(`/foco?minutes=${m.duration_minutes??45}&mission=${m.id}`)}><span className={`rank-chip rank-${m.rank.toLowerCase()}`}>{m.rank}</span><div><strong>{m.title}</strong><small>{m.duration_minutes??45} min · {m.priority}</small></div><Crosshair size={14}/></button>)}{!attrMissions.length&&<div className="empty-compact">Nenhuma missão aberta está ligada diretamente a este atributo. Você não precisa criar uma só para alimentar a barra.</div>}</div></SurfaceCard></>}
        {selectedReward&&<SurfaceCard tone="amber" className="entity-inspector"><div className="entity-inspector__header"><div><span className="eyebrow">Recompensa</span><h2>{selectedReward.name}</h2></div><button className="icon-button" onClick={()=>setSelection(null)}><X size={16}/></button></div><p className="panel-copy">{selectedReward.description}</p><div className="entity-inspector__meta"><span><Coins size={12}/>{selectedReward.cost} coins</span><span>Nível {selectedReward.minimum_level}+</span><span>Saldo: {profile?.nexus_coins??0}</span></div><button className="primary-button" disabled={(profile?.nexus_coins??0)<selectedReward.cost||(profile?.level??1)<selectedReward.minimum_level} onClick={()=>void redeem(selectedReward.id)}><Award size={15}/>{(profile?.nexus_coins??0)<selectedReward.cost?'Coins insuficientes':'Resgatar recompensa'}</button></SurfaceCard>}
        {selectedAchievement&&<SurfaceCard tone={selectedAchievement.unlocked_at?'green':'slate'} className="entity-inspector"><div className="entity-inspector__header"><div><span className="eyebrow">Conquista · {selectedAchievement.rarity}</span><h2>{selectedAchievement.name}</h2></div><button className="icon-button" onClick={()=>setSelection(null)}><X size={16}/></button></div><p className="panel-copy">{selectedAchievement.criteria||selectedAchievement.description}</p><div className="entity-inspector__meta"><span>+{selectedAchievement.xp_reward} XP</span><span>+{selectedAchievement.coin_reward} coins</span><span>{selectedAchievement.unlocked_at?`Desbloqueada em ${new Date(selectedAchievement.unlocked_at).toLocaleDateString('pt-BR')}`:'Ainda bloqueada'}</span></div></SurfaceCard>}
      </aside>}
    </section>
  </div>
}
