import { Award, CheckCircle2, Coins, LockKeyhole, ShieldCheck, Sparkles, Swords, Trophy, Zap } from 'lucide-react'
import { useMemo, useState } from 'react'
import { ProgressRing } from '../components/ProgressRing'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'

export function LifeRpgPage(){
  const {workspace,claimReward}=useNexus(); const [message,setMessage]=useState<string|null>(null); const profile=workspace.profile
  const currentLevelXp=(profile?.xp_total??0)%500; const levelPct=Math.round(currentLevelXp/500*100)
  const seasonXp=useMemo(()=>{if(!workspace.season?.starts_on)return 0; return workspace.activity.filter(e=>e.created_at.slice(0,10)>=(workspace.season?.starts_on??'')).reduce((s,e)=>s+Math.max(0,e.xp_delta),0)},[workspace.activity,workspace.season])
  const seasonPct=Math.min(100,Math.round(seasonXp/Math.max(workspace.season?.xp_goal??1,1)*100))
  const unlocked=workspace.achievements.filter(item=>item.unlocked_at)
  async function redeem(id:string){try{const reward=await claimReward(id);setMessage(`${reward} resgatada.`);setTimeout(()=>setMessage(null),3000)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível resgatar.')}}
  return <div className="page-stack rpg-page"><section className="rpg-hero"><div className="rpg-hero__sigil"><Sparkles size={29}/></div><div className="rpg-hero__identity"><span className="eyebrow">Player profile</span><h1>{profile?.display_name??'Jogador'}</h1><p>{profile?.class_name??'Tecelão'} · {profile?.title??'Iniciado da Trama'}</p>{profile?.motto&&<small className="rpg-motto">“{profile.motto}”</small>}<div className="level-track"><span style={{width:`${levelPct}%`}}/></div><small>{currentLevelXp} / 500 XP para o próximo nível</small></div><div className="rpg-hero__level"><span>NÍVEL</span><strong>{profile?.level??1}</strong><div><Coins size={13}/>{profile?.nexus_coins??0} coins</div></div></section>{message&&<div className="toast-message">{message}</div>}
  <section className="attribute-grid attribute-grid--rpg">{workspace.attributes.map(attr=><article className={`attribute-card tone-${attr.color??'slate'}`} key={attr.id}><div><span>{attr.icon&&<b className="attribute-symbol">{attr.icon}</b>}{attr.label}</span><strong>Nv. {attr.level}</strong></div><p>{attr.description}</p><div className="attribute-xp-track"><span style={{width:`${(attr.xp%400)/400*100}%`}}/></div><small>{attr.xp%400} / 400 XP</small></article>)}</section>
  <section className="split-grid"><SurfaceCard tone="violet" eyebrow="Temporada" title={workspace.season?.name??'Ascensão do Nexus'}><div className="ring-row"><ProgressRing value={seasonPct} label="temporada" detail={`${seasonXp} / ${workspace.season?.xp_goal??6000} XP`} size="lg"/><div className="journey-notes"><div><Swords size={16}/><span><strong>Boss final</strong>{workspace.season?.boss_name??'Consolidar o sistema'}</span></div><div><Trophy size={16}/><span><strong>Recompensa</strong>{workspace.season?.final_reward??'Experiência especial'}</span></div><div><Zap size={16}/><span><strong>Ritmo</strong>{workspace.activity.filter(e=>e.event_type==='mission.completed').length} missões registradas</span></div></div></div></SurfaceCard><SurfaceCard tone="amber" eyebrow="Cofre" title="Recompensas"><div className="reward-list">{workspace.rewards.map(reward=><button className="reward-card" key={reward.id} onClick={()=>void redeem(reward.id)} disabled={(profile?.nexus_coins??0)<reward.cost||(profile?.level??1)<reward.minimum_level}><span className="reward-icon"><Award size={16}/></span><div><strong>{reward.name}</strong><small>{reward.description}</small></div><span className="reward-cost"><Coins size={12}/>{reward.cost}</span></button>)}</div></SurfaceCard></section>
  <SurfaceCard tone="violet" eyebrow="Sala de conquistas" title={`${unlocked.length} / ${workspace.achievements.length} desbloqueadas`}><div className="achievement-grid">{workspace.achievements.map(item=><article className={`achievement-card ${item.unlocked_at?'is-unlocked':''}`} key={item.id}><span className="achievement-card__icon">{item.unlocked_at?<CheckCircle2 size={17}/>:<LockKeyhole size={17}/>}</span><div><div className="achievement-card__title"><strong>{item.name}</strong><span>{item.rarity}</span></div><p>{item.criteria}</p><small>+{item.xp_reward} XP · +{item.coin_reward} coins</small></div></article>)}</div></SurfaceCard>
  <section className="split-grid"><SurfaceCard eyebrow="Sistema" title="Regras vivas"><div className="system-rules"><div><ShieldCheck size={17}/><div><strong>Conclusão transacional</strong><span>Uma missão concede XP e moedas uma única vez, no banco.</span></div></div><div><Zap size={17}/><div><strong>Progressão conectada</strong><span>Atributo, projeto e jornada recebem o mesmo evento.</span></div></div><div><Trophy size={17}/><div><strong>Economia real</strong><span>Recompensas descontam coins atomicamente.</span></div></div></div></SurfaceCard><SurfaceCard tone="slate" eyebrow="Talentos" title="Próximos desbloqueios"><div className="talent-list"><div><span className="talent-icon"><LockKeyhole size={16}/></span><div><strong>Fluxo Profundo</strong><small>Desbloqueios contextuais virão por atributo.</small></div></div><div><span className="talent-icon"><LockKeyhole size={16}/></span><div><strong>Arquiteto de Rotina</strong><small>Combos baseados em consistência real.</small></div></div><div><span className="talent-icon"><LockKeyhole size={16}/></span><div><strong>Reserva Estratégica</strong><small>Marcos financeiros e recompensas conscientes.</small></div></div></div></SurfaceCard></section></div>
}
