import { ArrowRight, BriefcaseBusiness, CalendarClock, CirclePlus, Gauge, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'

export function ProjectsPage() {
  const { workspace, addProject, editProject } = useNexus()
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')
  const [busy, setBusy] = useState<string | null>(null)
  const active = useMemo(() => workspace.projects.filter((project) => !['Concluído','Arquivado'].includes(project.status)), [workspace.projects])
  const avg = active.length ? Math.round(active.reduce((sum,project)=>sum+project.progress,0)/active.length) : 0
  const withoutAction = active.filter((project)=>!project.next_action).length

  async function submit() { if(!name.trim()) return; setCreating(true); try { await addProject(name.trim()); setName('') } finally { setCreating(false) } }
  async function bump(id:string,current:number){setBusy(id); try{await editProject(id,{progress:Math.min(100,current+10)})}finally{setBusy(null)}}

  return <div className="page-stack projects-page"><section className="page-hero page-hero--violet"><div><span className="eyebrow">Resultados maiores</span><h1>Projetos</h1><p>Use projetos quando um resultado precisa de várias ações. Mantenha a próxima ação visível e atualize o progresso quando algo realmente avançar.</p></div><div className="page-hero__badge"><BriefcaseBusiness size={17}/> <span>{active.length} ativos</span></div></section><section className="projects-metrics"><SurfaceCard tone="violet"><span>Progresso médio</span><strong>{avg}%</strong><small>projetos ativos</small></SurfaceCard><SurfaceCard tone="amber"><span>Sem próxima ação</span><strong>{withoutAction}</strong><small>precisam de decisão</small></SurfaceCard><SurfaceCard tone="blue"><span>XP dos projetos</span><strong>{active.reduce((s,p)=>s+p.xp,0).toLocaleString('pt-BR')}</strong><small>acumulado</small></SurfaceCard></section><SurfaceCard tone="violet" className="project-create"><div><span className="eyebrow">Novo projeto</span><h2>Que resultado precisa de mais de uma ação para acontecer?</h2></div><div className="project-create__form"><input value={name} onChange={(e)=>setName(e.target.value)} onKeyDown={(e)=>e.key==='Enter'&&void submit()} placeholder="Nome do projeto…"/><button className="primary-button" disabled={creating||!name.trim()} onClick={()=>void submit()}><CirclePlus size={16}/> Criar</button></div></SurfaceCard><section className="project-portfolio-grid">{active.length ? active.map((project)=><article className="project-command-card" key={project.id}><div className="project-command-card__top"><span className={`rank-badge rank-${project.priority==='Crítica'?'S':project.priority==='Alta'?'A':project.priority==='Média'?'B':'C'}`}>{project.priority}</span><span>Nv. {project.level}</span></div><h3>{project.name}</h3><p>{project.description || 'Descreva o resultado esperado se isso ajudar a deixar o projeto claro.'}</p><div className="project-progress-line"><div><span>Progresso</span><strong>{project.progress}%</strong></div><div className="progress-bar"><span style={{width:`${project.progress}%`}}/></div></div><div className="project-next-action"><ArrowRight size={14}/><div><span>Próxima ação</span><strong>{project.next_action || 'Ainda não definida'}</strong></div></div><div className="project-command-card__footer"><span><Sparkles size={13}/>{project.xp} XP</span>{project.due_at&&<span><CalendarClock size={13}/>{new Date(project.due_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span>}<button disabled={busy===project.id||project.progress>=100} onClick={()=>void bump(project.id,project.progress)}><Gauge size={13}/> +10%</button></div></article>) : <SurfaceCard className="project-empty"><BriefcaseBusiness size={28}/><h3>Nenhum projeto ativo.</h3><p>Crie um projeto quando uma intenção não couber em uma única missão.</p></SurfaceCard>}</section></div>
}
