import { ArrowRight, Beaker, BookOpen, CalendarClock, CheckCircle2, Clock3, Crosshair, GraduationCap, Plus, Sparkles, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { SurfaceCard } from '../components/SurfaceCard'
import { useNexus } from '../context/NexusContext'
import { navigate } from '../lib/router'
import { getRoutineContext } from '../lib/routine-context'
import { emitUI } from '../lib/ui-events'
import type { AcademicEvent } from '../types/nexus'

const days=[{id:1,short:'SEG',label:'Segunda'},{id:2,short:'TER',label:'Terça'},{id:3,short:'QUA',label:'Quarta'},{id:4,short:'QUI',label:'Quinta'},{id:5,short:'SEX',label:'Sexta'},{id:6,short:'SÁB',label:'Sábado'}]
function displayTime(value:string){return value.slice(0,5)}
function eventDate(event:AcademicEvent){if(event.starts_at)return new Date(event.starts_at);if(event.event_date)return new Date(`${event.event_date}T12:00:00-03:00`);return null}
function eventWhen(event:AcademicEvent){const date=eventDate(event);if(!date)return'Data não definida';return new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'short',...(event.starts_at?{hour:'2-digit',minute:'2-digit'}:{}),timeZone:'America/Sao_Paulo'}).format(date).replace('.','')}
function eventIso(event:AcademicEvent){const date=eventDate(event);return date?new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(date):''}
function daysUntil(event:AcademicEvent){const date=eventDate(event);if(!date)return null;return Math.max(0,Math.ceil((date.getTime()-Date.now())/86_400_000))}

export function StudiesPage(){
  const {workspace}=useNexus();const currentWeekday=new Date().getDay();const [selectedDay,setSelectedDay]=useState(()=>currentWeekday>=1&&currentWeekday<=6?currentWeekday:1);const [selectedEventId,setSelectedEventId]=useState<string|null>(null)
  const schedule=workspace.academicSchedule;const events=workspace.academicEvents;const context=getRoutineContext(workspace)
  const selectedSchedule=useMemo(()=>schedule.filter(item=>item.weekday===selectedDay),[schedule,selectedDay]);const classes=selectedSchedule.filter(item=>item.schedule_type==='class');const extras=selectedSchedule.filter(item=>item.schedule_type!=='class')
  const upcoming=useMemo(()=>events.filter(event=>{const date=eventDate(event);return date?date.getTime()>=Date.now()-60*60*1000:false}).sort((a,b)=>(eventDate(a)?.getTime()??Infinity)-(eventDate(b)?.getTime()??Infinity)).slice(0,12),[events])
  const nextEvent=upcoming[0];const selectedEvent=events.find(event=>event.id===selectedEventId)??null;const completedEvents=events.filter(event=>event.status==='Concluído').length
  const relevantMissions=selectedEvent?workspace.missions.filter(m=>{const words=selectedEvent.title.toLowerCase().split(/\W+/).filter(w=>w.length>3);return words.some(w=>`${m.title} ${m.notes??''}`.toLowerCase().includes(w))}).slice(0,5):[]
  const studyNow=context.suggestion.kind==='focus'?context.suggestion:null
  function inspectEvent(event:AcademicEvent){setSelectedEventId(event.id);if(window.matchMedia('(max-width:760px)').matches)window.setTimeout(()=>document.querySelector('.academic-event-inspector')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}

  return <div className="page-stack studies-page studies-page--consultable">
    <section className="page-hero page-hero--blue academic-hero"><div><span className="eyebrow">Escola e estudos</span><h1>Estudos</h1><p>Consulte o dia, abra provas e simulados, veja o que já está ligado a eles e crie preparação sem sair da tela.</p></div><div className="academic-hero__summary"><GraduationCap size={18}/><div><span>{studyNow?'Janela de estudo agora':'Próxima pressão'}</span><strong>{studyNow?.title??nextEvent?.title??'Nenhum próximo evento'}</strong><small>{studyNow?`${studyNow.durationMinutes??45} min sugeridos`:nextEvent?eventWhen(nextEvent):'calendário livre'}</small></div></div></section>

    {studyNow&&<SurfaceCard tone="violet" className="academic-now"><div><Crosshair size={18}/><div><span className="eyebrow">Cabe agora</span><strong>{studyNow.title}</strong><p>{studyNow.detail}</p></div><button className="primary-button" onClick={()=>navigate(studyNow.actionPath??'/foco')}>Começar</button></SurfaceCard>}

    <section className="academic-metrics"><SurfaceCard tone="blue"><span>Aulas na semana</span><strong>{schedule.filter(i=>i.schedule_type==='class').length}</strong><small>horários cadastrados</small></SurfaceCard><SurfaceCard tone="violet"><span>Plantões e blocos</span><strong>{schedule.filter(i=>i.schedule_type!=='class').length}</strong><small>fora da grade regular</small></SurfaceCard><SurfaceCard tone="green"><span>Simulados concluídos</span><strong>{completedEvents}</strong><small>em 2026</small></SurfaceCard><SurfaceCard tone="amber"><span>Próxima prova</span><strong>{nextEvent?daysUntil(nextEvent):'—'}</strong><small>{nextEvent?'dias restantes':'sem evento próximo'}</small></SurfaceCard></section>

    <section className="academic-layout"><SurfaceCard className="academic-timetable" tone="blue" eyebrow="Horários" title="Grade da semana"><div className="academic-day-tabs" role="tablist">{days.map(day=><button key={day.id} className={selectedDay===day.id?'active':''} onClick={()=>setSelectedDay(day.id)}><span>{day.short}</span><small>{day.label}</small></button>)}</div><div className="academic-day-heading"><div><span className="eyebrow">{days.find(day=>day.id===selectedDay)?.label}</span><h3>{classes.length} aulas</h3></div>{selectedDay===currentWeekday&&<span className="academic-today-chip">Hoje</span>}</div><div className="academic-class-list">{classes.map((item,index)=><article className="academic-class-row" key={item.id}><div className="academic-time"><strong>{displayTime(item.start_time)}</strong><small>{item.end_time?displayTime(item.end_time):''}</small></div><span className="academic-line"><i/>{index<classes.length-1&&<b/>}</span><div className="academic-class-copy"><strong>{item.subject}</strong><small>Aula regular</small></div></article>)}{!classes.length&&<div className="empty-compact"><BookOpen size={16}/>Sem aulas regulares neste dia.</div>}</div>{extras.length>0&&<div className="academic-extras"><span className="eyebrow">Depois das aulas</span>{extras.map(item=><article key={item.id}><span className={`academic-extra-icon academic-extra-icon--${item.schedule_type}`}><Beaker size={14}/></span><div><strong>{item.subject}</strong><small><Clock3 size={11}/>{displayTime(item.start_time)}{item.end_time?`–${displayTime(item.end_time)}`:''}{item.note?` · ${item.note}`:''}</small></div></article>)}</div>}</SurfaceCard><aside className="academic-side"><SurfaceCard tone="violet" eyebrow="Rotina semanal" title="Blocos de estudo"><div className="academic-rules"><div><span>Terça</span><strong>Matemática · História · Química</strong><small>pela urgência e dificuldade</small></div><div><span>Quarta</span><strong>Bio Vest · 15h30</strong><small>bloco fixo</small></div><div><span>Quinta</span><strong>Física + plantões</strong><small>dúvidas concretas</small></div><div><span>Sexta</span><strong>Redação ou revisão</strong><small>um bloco, não dois</small></div><div><span>Domingo</span><strong>Bloco principal</strong><small>sem ocupar o dia inteiro</small></div></div></SurfaceCard></aside></section>

    <section className={`academic-events-workspace ${selectedEvent?'has-inspector':''}`}>
      <SurfaceCard tone="cyan" eyebrow="Calendário" title="Próximos simulados e provas" action={<span className="surface-chip"><CalendarClock size={12}/><span>{upcoming.length}</span></span>}><div className="academic-event-list">{upcoming.map((event,index)=><button className={`academic-event academic-event--button ${index===0?'academic-event--next':''} ${selectedEventId===event.id?'selected':''}`} key={event.id} onClick={()=>inspectEvent(event)}><div className="academic-event__date"><strong>{eventDate(event)?.getDate().toString().padStart(2,'0')}</strong><span>{eventDate(event)?.toLocaleDateString('pt-BR',{month:'short',timeZone:'America/Sao_Paulo'}).replace('.','')}</span></div><div className="academic-event__body"><div><span className={`academic-status academic-status--${event.status.toLowerCase()}`}>{event.status}</span>{event.format&&<span className="academic-format">{event.format}</span>}</div><strong>{event.title}</strong><small>{eventWhen(event)}{event.note?` · ${event.note}`:''}</small></div><ArrowRight size={15}/></button>)}{!upcoming.length&&<div className="empty-compact">Nenhum compromisso acadêmico futuro cadastrado.</div>}</div></SurfaceCard>

      {selectedEvent&&<aside className="academic-event-inspector"><SurfaceCard tone="amber" className="entity-inspector"><div className="entity-inspector__header"><div><span className="eyebrow">Evento acadêmico</span><h2>{selectedEvent.title}</h2></div><button className="icon-button" onClick={()=>setSelectedEventId(null)}><X size={16}/></button></div><div className="entity-inspector__meta"><span>{eventWhen(selectedEvent)}</span><span>{daysUntil(selectedEvent)} dias</span>{selectedEvent.format&&<span>{selectedEvent.format}</span>}</div>{selectedEvent.note&&<p className="panel-copy">{selectedEvent.note}</p>}<div className="entity-inspector__actions"><button className="primary-button" onClick={()=>emitUI('quickAdd',{type:'mission',dueDate:eventIso(selectedEvent),title:`Preparar ${selectedEvent.title}`})}><Plus size={15}/>Criar preparação</button><button className="secondary-button" onClick={()=>navigate(`/calendario?date=${eventIso(selectedEvent)}`)}><CalendarClock size={15}/>Ver dia</button></div></SurfaceCard><SurfaceCard tone="violet" eyebrow="Ligadas" title={`${relevantMissions.length} missões relacionadas`}><div className="project-linked-missions">{relevantMissions.map(m=><button key={m.id} onClick={()=>navigate(`/foco?minutes=${m.duration_minutes??45}&mission=${m.id}`)}><span className={`rank-chip rank-${m.rank.toLowerCase()}`}>{m.rank}</span><div><strong>{m.title}</strong><small>{m.status} · {m.duration_minutes??45} min</small></div><Crosshair size={14}/></button>)}{!relevantMissions.length&&<div className="empty-compact">Nenhuma missão claramente ligada. Crie uma preparação apenas se ela realmente precisar existir.</div>}</div></SurfaceCard></aside>}
    </section>
  </div>
}
